let allGoodsTest = { 
    // Мужская одежда
    "1" : {src: './../menCategory/assets/img/Футболка_1.png', name: 'VERSACE JEANS COUTURE', catigories: 'Фуфайка (Футболка)', price:'14590', dataCatigories:'men', class: 'goods__block tshirts_men'},
    "2" : {src: './../menCategory/assets/img/Футболка_2.png', name: 'Guess Jeans',           catigories: 'Хлопковая футболка', price:'6890',  dataCatigories:'men', class: 'goods__block tshirts_men'},
    "3" : {src: './../menCategory/assets/img/Футболка_3.png', name: 'Guess Jeans',           catigories: 'Хлопковая футболка', price:'6290',  dataCatigories:'men', class: 'goods__block tshirts_men'},
    "4" : {src: './../menCategory/assets/img/Футболка_4.png', name: 'HUGO',                  catigories: 'Хлопковая футболка', price:'6790',  dataCatigories:'men', class: 'goods__block tshirts_men'},
    "5" : {src: './../menCategory/assets/img/Футболка_5.png', name: 'Guess Jeans',           catigories: 'Хлопковая футболка', price:'5690',  dataCatigories:'men', class: 'goods__block tshirts_men'},
    "6" : {src: './../menCategory/assets/img/Футболка_6.png', name: `Marc O'Polo`,           catigories: 'Фуфайка (Футболка)', price:'10590', dataCatigories:'men', class: 'goods__block tshirts_men'},
    "7" : {src: './../menCategory/assets/img/Футболка_7.png', name: 'Esprit Edc',            catigories: 'Фуфайка (Футболка)', price:'2990',  dataCatigories:'men', class: 'goods__block tshirts_men'},
    "8" : {src: './../menCategory/assets/img/Футболка_8.png', name: `Marc O'Polo`,           catigories: 'Хлопковая футболка', price:'5490',  dataCatigories:'men', class: 'goods__block tshirts_men'},
    "9" : {src: './../menCategory/assets/img/Футболка_9.png', name: 'BOSS',                  catigories: 'Фуфайка (Футболка)', price:'8790',  dataCatigories:'men', class: 'goods__block tshirts_men'},

    "10" : {src: './../menCategory/assets/img/Куртка_1.png', name: 'VARSITY NYLON BOMBER JACKET',        catigories: 'Куртка', price:'16200', dataCatigories:'men', class: 'goods__block jacket_men'},
    "11" : {src: './../menCategory/assets/img/Куртка_2.png', name: 'VARSITY LOGO BOMBER JACKET',         catigories: 'Куртка', price:'23100', dataCatigories:'men', class: 'goods__block jacket_men'},
    "12" : {src: './../menCategory/assets/img/Куртка_3.png', name: 'VERSACE ALLOVER BOMBER JACKET',      catigories: 'Куртка', price:'16200', dataCatigories:'men', class: 'goods__block jacket_men'},
    "13" : {src: './../menCategory/assets/img/Куртка_4.png', name: 'BAROCCO 660 WINDBREAKER JACKET',     catigories: 'Куртка', price:'12800', dataCatigories:'men', class: 'goods__block jacket_men'},
    "14" : {src: './../menCategory/assets/img/Куртка_5.png', name: 'BAROCCO 660 QUILTED BLOUSON JACKET', catigories: 'Куртка', price:'25500', dataCatigories:'men', class: 'goods__block jacket_men'},
    "15" : {src: './../menCategory/assets/img/Куртка_6.png', name: 'NYLON GRAPHIC LOGO BLOUSON JACKET',  catigories: 'Куртка', price:'19600', dataCatigories:'men', class: 'goods__block jacket_men'},
    "16" : {src: './../menCategory/assets/img/Куртка_7.png', name: 'MEDUSA BLOUSON PUFFER JACKET',       catigories: 'Куртка', price:'23000', dataCatigories:'men', class: 'goods__block jacket_men'},
    "17" : {src: './../menCategory/assets/img/Куртка_8.png', name: 'LA GRECA PUFFER JACKET',             catigories: 'Куртка', price:'15300', dataCatigories:'men', class: 'goods__block jacket_men'},
    "18" : {src: './../menCategory/assets/img/Куртка_9.png', name: 'LOGO WINDBREAKER JACKET',            catigories: 'Куртка', price:'21300', dataCatigories:'men', class: 'goods__block jacket_men'},

    "19" : {src: './../menCategory/assets/img/Толстовка_1.png', name: 'VARSITY LOGO SWEATSHIRT',       catigories: 'Толстовки', price:'6400', dataCatigories:'men', class: 'goods__block hoodies_men'},
    "20" : {src: './../menCategory/assets/img/Толстовка_2.png', name: 'STUDDED VARSITY LOGO HOODIE',   catigories: 'Толстовки', price:'10200', dataCatigories:'men', class: 'goods__block hoodies_men'},
    "21" : {src: './../menCategory/assets/img/Толстовка_3.png', name: 'MEDUSA HOODIE',                 catigories: 'Толстовки', price:'7200', dataCatigories:'men', class: 'goods__block hoodies_men'},
    "22" : {src: './../menCategory/assets/img/Толстовка_4.png', name: 'BAROQUE CRYSTAL GRID HOODIE',   catigories: 'Толстовки', price:'12800', dataCatigories:'men', class: 'goods__block hoodies_men'},
    "23" : {src: './../menCategory/assets/img/Толстовка_5.png', name: 'SAFETY PIN GRAPHIC SWEATSHIRT', catigories: 'Толстовки', price:'5800', dataCatigories:'men', class: 'goods__block hoodies_men'},
    "24" : {src: './../menCategory/assets/img/Толстовка_6.png', name: 'MEDUSA GRAPHIC SWEATSHIRT',     catigories: 'Толстовки', price:'6400', dataCatigories:'men', class: 'goods__block hoodies_men'},
    "25" : {src: './../menCategory/assets/img/Толстовка_7.png', name: 'MEDUSA LOGO SWEATSHIRT',        catigories: 'Толстовки', price:'8400', dataCatigories:'men', class: 'goods__block hoodies_men'},
    "26" : {src: './../menCategory/assets/img/Толстовка_8.png', name: 'LA MASCHERA LOGO SWEATSHIRT',   catigories: 'Толстовки', price:'6700', dataCatigories:'men', class: 'goods__block hoodies_men'},
    "27" : {src: './../menCategory/assets/img/Толстовка_9.png', name: 'MEDUSA HOODIE',                 catigories: 'Толстовки', price:'7200', dataCatigories:'men', class: 'goods__block hoodies_men'},

    "28" : {src: './../menCategory/assets/img/Джинсы_1.png', name: 'VERSACE WIDE-LEG JEANS',   catigories: 'Джинсы', price:'5500', dataCatigories:'men', class: 'goods__block jeans_men'},
    "29" : {src: './../menCategory/assets/img/Джинсы_2.png', name: 'MEDUSA SLIM-FIT JEANS',    catigories: 'Джинсы', price:'4600', dataCatigories:'men', class: 'goods__block jeans_men'},
    "30" : {src: './../menCategory/assets/img/Джинсы_3.png', name: 'MEDUSA JEANS',             catigories: 'Джинсы', price:'5000', dataCatigories:'men', class: 'goods__block jeans_men'},
    "31" : {src: './../menCategory/assets/img/Джинсы_4.png', name: 'LA GRECA LASERED JEANS',   catigories: 'Джинсы', price:'7500', dataCatigories:'men', class: 'goods__block jeans_men'},
    "32" : {src: './../menCategory/assets/img/Джинсы_5.png', name: 'LA MEDUSA SLIM-FIT JEANS', catigories: 'Джинсы', price:'4200', dataCatigories:'men', class: 'goods__block jeans_men'},
    "33" : {src: './../menCategory/assets/img/Джинсы_6.png', name: 'STUDDED MEDUSA JEANS',     catigories: 'Джинсы', price:'5800', dataCatigories:'men', class: 'goods__block jeans_men'},
    "34" : {src: './../menCategory/assets/img/Джинсы_7.png', name: 'VERSACE ALLOVER JEANS',    catigories: 'Джинсы', price:'10600',dataCatigories:'men', class: 'goods__block jeans_men'},
    "35" : {src: './../menCategory/assets/img/Джинсы_8.png', name: 'SLIM FIT BLACK JEANS',     catigories: 'Джинсы', price:'4200', dataCatigories:'men', class: 'goods__block jeans_men'},
    "36" : {src: './../menCategory/assets/img/Джинсы_9.png', name: 'MEDUSA TWISTED JEANS',     catigories: 'Джинсы', price:'2900', dataCatigories:'men', class: 'goods__block jeans_men'},

    "37" : {src: './../menCategory/assets/img/Дом_одежда_1.png', name: 'BAROCCO 660 SILK PAJAMA TOP',     catigories: 'Домашняя одежда', price:'9800',  dataCatigories:'men',  class: 'goods__block homclot_men'},
    "38" : {src: './../menCategory/assets/img/Дом_одежда_2.png', name: 'BAROCCO 660 SILK PAJAMA BOTTOMS', catigories: 'Домашняя одежда', price:'7600',  dataCatigories:'men',  class: 'goods__block homclot_men'},
    "39" : {src: './../menCategory/assets/img/Дом_одежда_3.png', name: 'MASCHERA BAROQUE PYJAMA TOP',     catigories: 'Домашняя одежда', price:'11000', dataCatigories:'men', class: 'goods__block homclot_men'},
    "40" : {src: './../menCategory/assets/img/Дом_одежда_4.png', name: 'MASCHERA BAROQUE PYJAMA TOP',     catigories: 'Домашняя одежда', price:'8400',  dataCatigories:'men',  class: 'goods__block homclot_men'},
    "41" : {src: './../menCategory/assets/img/Дом_одежда_5.png', name: 'MEDUSA UNDERSHIRT 2-PACK',        catigories: 'Домашняя одежда', price:'900',   dataCatigories:'men',   class: 'goods__block homclot_men'},
    "42" : {src: './../menCategory/assets/img/Дом_одежда_6.png', name: 'EDUSA UNDERSHIRT 2-PACK',         catigories: 'Домашняя одежда', price:'900',   dataCatigories:'men',   class: 'goods__block homclot_men'},
    "43" : {src: './../menCategory/assets/img/Дом_одежда_7.png', name: 'MEDUSA SLEEVELESS UNDERSHIRT',    catigories: 'Домашняя одежда', price:'500',   dataCatigories:'men',   class: 'goods__block homclot_men'},
    "44" : {src: './../menCategory/assets/img/Дом_одежда_8.png', name: 'BAROCCO SILK ROBE',               catigories: 'Домашняя одежда', price:'11900', dataCatigories:'men', class: 'goods__block homclot_men'},
    "45" : {src: './../menCategory/assets/img/Дом_одежда_9.png', name: 'LA GRECA SILK PAJAMA TOP',        catigories: 'Домашняя одежда', price:'4900',  dataCatigories:'men',  class: 'goods__block homclot_men'},
    
    "46" : {src: './../menCategory/assets/img/Обувь_1.png', name: 'ODISSEA SNEAKERS',                  catigories: 'Обувь', price:'6100',  dataCatigories:'men', class: 'goods__block shoes_men'},
    "47" : {src: './../menCategory/assets/img/Обувь_2.png', name: 'CRYSTAL ODISSEA SNEAKERS',          catigories: 'Обувь', price:'15200', dataCatigories:'men', class: 'goods__block shoes_men'},
    "48" : {src: './../menCategory/assets/img/Обувь_3.png', name: 'GRECA ODISSEA SNEAKERS',            catigories: 'Обувь', price:'5000',  dataCatigories:'men', class: 'goods__block shoes_men'},
    "49" : {src: './../menCategory/assets/img/Обувь_4.png', name: 'ODISSEA SNEAKERS',                  catigories: 'Обувь', price:'6100',  dataCatigories:'men', class: 'goods__block shoes_men'},
    "50" : {src: './../menCategory/assets/img/Обувь_5.png', name: 'GRECA ODISSEA SNEAKERS',            catigories: 'Обувь', price:'5000',  dataCatigories:'men', class: 'goods__block shoes_men'},
    "51" : {src: './../menCategory/assets/img/Обувь_6.png', name: 'TRIGRECA SNEAKERS',                 catigories: 'Обувь', price:'6900',  dataCatigories:'men', class: 'goods__block shoes_men'},
    "52" : {src: './../menCategory/assets/img/Обувь_7.png', name: 'TRIGRECA SNEAKERS',                 catigories: 'Обувь', price:'6700',  dataCatigories:'men', class: 'goods__block shoes_men'},
    "53" : {src: './../menCategory/assets/img/Обувь_8.png', name: 'TRIGRECA SNEAKERS',                 catigories: 'Обувь', price:'6700',  dataCatigories:'men', class: 'goods__block shoes_men'},
    "54" : {src: './../menCategory/assets/img/Обувь_9.png', name: 'VERSACE ALLOVER LA GRECA SNEAKERS', catigories: 'Обувь', price:'4100',  dataCatigories:'men', class: 'goods__block shoes_men'},

    "55" : {src: './../menCategory/assets/img/Брюки_1.png', name: 'MEDUSA LA GRECA CARGO TROUSERS',      catigories: 'Брюки', price:'7500', dataCatigories:'men', class: 'goods__block pants_men'},
    "56" : {src: './../menCategory/assets/img/Брюки_2.png', name: 'VERSACE ALLOVER TERRY SWEATPANTS',    catigories: 'Брюки', price:'6700', dataCatigories:'men', class: 'goods__block pants_men'},
    "57" : {src: './../menCategory/assets/img/Брюки_3.png', name: 'MEDUSA SLIM-FIT PANTS',               catigories: 'Брюки', price:'5500', dataCatigories:'men', class: 'goods__block pants_men'},
    "58" : {src: './../menCategory/assets/img/Брюки_4.png', name: 'LA GRECA PANTS',                      catigories: 'Брюки', price:'6700', dataCatigories:'men', class: 'goods__block pants_men'},
    "59" : {src: './../menCategory/assets/img/Брюки_5.png', name: 'LOGO SWEATPANTS',                     catigories: 'Брюки', price:'6400', dataCatigories:'men', class: 'goods__block pants_men'},
    "60" : {src: './../menCategory/assets/img/Брюки_6.png', name: 'NYLON CARGO PANTS',                   catigories: 'Брюки', price:'9300', dataCatigories:'men', class: 'goods__block pants_men'},
    "61" : {src: './../menCategory/assets/img/Брюки_7.png', name: 'SUIT TROUSERS',                       catigories: 'Брюки', price:'3200', dataCatigories:'men', class: 'goods__block pants_men'},
    "62" : {src: './../menCategory/assets/img/Брюки_8.png', name: 'MEDUSA BIGGIE LOGO SWEATPANTS',       catigories: 'Брюки', price:'2900', dataCatigories:'men', class: 'goods__block pants_men'},
    "63" : {src: './../menCategory/assets/img/Брюки_9.png', name: 'PASTEL PINSTRIPE FLANNEL WOOL PANTS', catigories: 'Брюки', price:'6600', dataCatigories:'men', class: 'goods__block pants_men'},

    // Женская одежда
    "400" : {src: './../womenCategory/assets/img/Футболка_1.png', name: 'VERSACE GODDESS OVERSIZED T-SHIRT', catigories: 'Фуфайка (Футболка)', price:'5600',  dataCatigories:'women', class: 'goods__block tshirts_women'},
    "401" : {src: './../womenCategory/assets/img/Футболка_2.png', name: 'CRYSTAL MEDUSA LOGO T-SHIRT',       catigories: 'Хлопковая футболка', price:'10400', dataCatigories:'women', class: 'goods__block tshirts_women'},
    "402" : {src: './../womenCategory/assets/img/Футболка_3.png', name: 'SPRING FESTIVAL RABBIT T-SHIRT',    catigories: 'Хлопковая футболка', price:'7700',  dataCatigories:'women', class: 'goods__block tshirts_women'},
    "403" : {src: './../womenCategory/assets/img/Футболка_4.png', name: 'CRYSTAL VERSACE ALLOVER T-SHIRT',   catigories: 'Хлопковая футболка', price:'11700', dataCatigories:'women', class: 'goods__block tshirts_women'},
    "404" : {src: './../womenCategory/assets/img/Футболка_5.png', name: 'SPRING FESTIVAL RABBIT T-SHIRT',    catigories: 'Хлопковая футболка', price:'5600',  dataCatigories:'women', class: 'goods__block tshirts_women'},
    "405" : {src: './../womenCategory/assets/img/Футболка_6.png', name: `DISTRESSED LOGO T-SHIRT`,           catigories: 'Фуфайка (Футболка)', price:'5600',  dataCatigories:'women', class: 'goods__block tshirts_women'},
    "406" : {src: './../womenCategory/assets/img/Футболка_7.png', name: 'STUDDED MEDUSA CROP TOP',           catigories: 'Фуфайка (Футболка)', price:'7700',  dataCatigories:'women', class: 'goods__block tshirts_women'},
    "407" : {src: './../womenCategory/assets/img/Футболка_8.png', name: `CRYSTAL MEDUSA T-SHIRT`,            catigories: 'Хлопковая футболка', price:'7700',  dataCatigories:'women', class: 'goods__block tshirts_women'},
    "408" : {src: './../womenCategory/assets/img/Футболка_9.png', name: '"TI AMO" T-SHIRT',                  catigories: 'Фуфайка (Футболка)', price:'3900',  dataCatigories:'women', class: 'goods__block tshirts_women'},

    "409" : {src: './../womenCategory/assets/img/Куртка_1.png', name: 'VERSACE ALLOVER DENIM JACKET',        catigories: 'Куртка', price:'14700', dataCatigories:'women', class: 'goods__block jacket_women'},
    "410" : {src: './../womenCategory/assets/img/Куртка_2.png', name: 'BAROCCO REVERSIBLE BOMBER JACKET',    catigories: 'Куртка', price:'20000', dataCatigories:'women', class: 'goods__block jacket_women'},
    "411" : {src: './../womenCategory/assets/img/Куртка_3.png', name: 'SPRING FESTIVAL RABBIT BOMBER JACKET',catigories: 'Куртка', price:'19100', dataCatigories:'women', class: 'goods__block jacket_women'},
    "412" : {src: './../womenCategory/assets/img/Куртка_4.png', name: 'MEDUSA WINDBREAKER JACKET',           catigories: 'Куртка', price:'16100', dataCatigories:'women', class: 'goods__block jacket_women'},
    "413" : {src: './../womenCategory/assets/img/Куртка_5.png', name: 'LOGO PUFFER JACKET',                  catigories: 'Куртка', price:'13000', dataCatigories:'women', class: 'goods__block jacket_women'},
    "414" : {src: './../womenCategory/assets/img/Куртка_6.png', name: 'MEDUSA LEATHER BIKER JACKET',         catigories: 'Куртка', price:'30400', dataCatigories:'women', class: 'goods__block jacket_women'},
    "415" : {src: './../womenCategory/assets/img/Куртка_7.png', name: 'MEDUSA LONG WOOL COAT',               catigories: 'Куртка', price:'26000', dataCatigories:'women', class: 'goods__block jacket_women'},
    "416" : {src: './../womenCategory/assets/img/Куртка_8.png', name: 'REVERSIBLE MEDUSA ORCHID JACKET',     catigories: 'Куртка', price:'24300', dataCatigories:'women', class: 'goods__block jacket_women'},
    "417" : {src: './../womenCategory/assets/img/Куртка_9.png', name: 'VERSACE GODDESS CROP BOMBER JACKET',  catigories: 'Куртка', price:'19100', dataCatigories:'women', class: 'goods__block jacket_women'},

    "418" : {src: './../womenCategory/assets/img/Толстовка_1.png', name: 'VERSACE GODDESS HOODIE',              catigories: 'Толстовки', price:'8600',  dataCatigories:'women', class: 'goods__block hoodies_women'},
    "419" : {src: './../womenCategory/assets/img/Толстовка_2.png', name: 'LOGO HOODIE',                         catigories: 'Толстовки', price:'8600',  dataCatigories:'women', class: 'goods__block hoodies_women'},
    "420" : {src: './../womenCategory/assets/img/Толстовка_3.png', name: 'DISTRESSED SLASHED OVERSIZED HOODIE', catigories: 'Толстовки', price:'13500', dataCatigories:'women', class: 'goods__block hoodies_women'},
    "421" : {src: './../womenCategory/assets/img/Толстовка_4.png', name: 'STUDDED DISTRESSED LOGO HOODIE',      catigories: 'Толстовки', price:'11700', dataCatigories:'women', class: 'goods__block hoodies_women'},
    "422" : {src: './../womenCategory/assets/img/Толстовка_5.png', name: 'VERSACE GODDESS STUDDED CROP HOODIE', catigories: 'Толстовки', price:'10800', dataCatigories:'women', class: 'goods__block hoodies_women'},
    "423" : {src: './../womenCategory/assets/img/Толстовка_6.png', name: 'STUDDED DISTRESSED LOGO HOODIE',      catigories: 'Толстовки', price:'11700', dataCatigories:'women', class: 'goods__block hoodies_women'},
    "424" : {src: './../womenCategory/assets/img/Толстовка_7.png', name: 'SPRING FESTIVAL RABBIT KNIT SWEATERS',catigories: 'Толстовки', price:'10000', dataCatigories:'women', class: 'goods__block hoodies_women'},
    "425" : {src: './../womenCategory/assets/img/Толстовка_8.png', name: 'LA GRECA MEDUSA JACQUARD SWEATER',    catigories: 'Толстовки', price:'6000',  dataCatigories:'women', class: 'goods__block hoodies_women'},
    "426" : {src: './../womenCategory/assets/img/Толстовка_9.png', name: 'SLASHED KNIT SWEATER',                catigories: 'Толстовки', price:'10800', dataCatigories:'women', class: 'goods__block hoodies_women'},

    "427" : {src: './../womenCategory/assets/img/Джинсы_1.png', name: 'CRYSTAL VERSACE ALLOVER JEANS',   catigories: 'Джинсы', price:'10000', dataCatigories:'women', class: 'goods__block jeans_women'},
    "428" : {src: './../womenCategory/assets/img/Джинсы_2.png', name: 'SLASHED WIDE-LEG JEANS',          catigories: 'Джинсы', price:'8200',  dataCatigories:'women', class: 'goods__block jeans_women'},
    "429" : {src: './../womenCategory/assets/img/Джинсы_3.png', name: 'VERSACE ALLOVER FLARED JEANS',    catigories: 'Джинсы', price:'10000', dataCatigories:'women', class: 'goods__block jeans_women'},
    "430" : {src: './../womenCategory/assets/img/Джинсы_4.png', name: 'MEDUSA PANELLED SKINNY JEANS',    catigories: 'Джинсы', price:'6900',  dataCatigories:'women', class: 'goods__block jeans_women'},
    "431" : {src: './../womenCategory/assets/img/Джинсы_5.png', name: 'MEDUSA STUDDED SKINNY JEANS',     catigories: 'Джинсы', price:'8200',  dataCatigories:'women', class: 'goods__block jeans_women'},
    "432" : {src: './../womenCategory/assets/img/Джинсы_6.png', name: 'VERSACE ALLOVER WIDE-LEG JEANS',  catigories: 'Джинсы', price:'10000', dataCatigories:'women', class: 'goods__block jeans_women'},
    "433" : {src: './../womenCategory/assets/img/Джинсы_7.png', name: 'VERSACE ALLOVER DENIM MINI SKIRT',catigories: 'Джинсы', price:'7700',  dataCatigories:'women', class: 'goods__block jeans_women'},
    "434" : {src: './../womenCategory/assets/img/Джинсы_8.png', name: 'MEDUSA DENIM SHORTS',             catigories: 'Джинсы', price:'5600',  dataCatigories:'women', class: 'goods__block jeans_women'},
    "435" : {src: './../womenCategory/assets/img/Джинсы_9.png', name: 'VERSACE ALLOVER FLARED JEANS',    catigories: 'Джинсы', price:'10000', dataCatigories:'women', class: 'goods__block jeans_women'},

    "436" : {src: './../womenCategory/assets/img/Дом_одежда_1.png', name: 'BAROCCO SILK PYJAMA SLIP DRESS',    catigories: 'Домашняя одежда', price:'5000',   dataCatigories:'women', class: 'goods__block homclot_women'},
    "437" : {src: './../womenCategory/assets/img/Дом_одежда_2.png', name: 'BAROCCO PRINT SILK PYJAMA BOTTOMS', catigories: 'Домашняя одежда', price:'7800',   dataCatigories:'women', class: 'goods__block homclot_women'},
    "438" : {src: './../womenCategory/assets/img/Дом_одежда_3.png', name: 'BAROCCO JACQUARD CROP PYJAMA TOP',  catigories: 'Домашняя одежда', price:'6000',   dataCatigories:'women', class: 'goods__block homclot_women'},
    "439" : {src: './../womenCategory/assets/img/Дом_одежда_4.png', name: 'BAROCCO PRINT SILK PYJAMA SHIRT',   catigories: 'Домашняя одежда', price:'10000',  dataCatigories:'women', class: 'goods__block homclot_women'},
    "440" : {src: './../womenCategory/assets/img/Дом_одежда_5.png', name: 'BAROCCO PRINT SILK PYJAMA SHORTS',  catigories: 'Домашняя одежда', price:'3800',   dataCatigories:'women', class: 'goods__block homclot_women'},
    "441" : {src: './../womenCategory/assets/img/Дом_одежда_6.png', name: 'BAROCCO PRINT SILK UNDERSHIRT',     catigories: 'Домашняя одежда', price:'3200',   dataCatigories:'women', class: 'goods__block homclot_women'},
    "442" : {src: './../womenCategory/assets/img/Дом_одежда_7.png', name: 'GRECA BORDER BAROCCO PYJAMA SHORTS',catigories: 'Домашняя одежда', price:'3400',   dataCatigories:'women', class: 'goods__block homclot_women'},
    "443" : {src: './../womenCategory/assets/img/Дом_одежда_8.png', name: 'GRECA BORDER SPORTS BRA',           catigories: 'Домашняя одежда', price:'600',    dataCatigories:'women', class: 'goods__block homclot_women'},
    "444" : {src: './../womenCategory/assets/img/Дом_одежда_9.png', name: 'CRYSTAL I ♡ BAROQUE BATHROBE',      catigories: 'Домашняя одежда', price:'5900',   dataCatigories:'women', class: 'goods__block homclot_women'},

    "445" : {src: './../womenCategory/assets/img/Обувь_1.png', name: 'GRECA CHELSEA BOOTS',                   catigories: 'Обувь', price:'8200',  dataCatigories:'women', class: 'goods__block shoes_women'},
    "446" : {src: './../womenCategory/assets/img/Обувь_2.png', name: 'TRIGRECA SNEAKERS',                     catigories: 'Обувь', price:'6800',  dataCatigories:'women', class: 'goods__block shoes_women'},
    "447" : {src: './../womenCategory/assets/img/Обувь_3.png', name: 'TRIGRECA SNEAKERS',                     catigories: 'Обувь', price:'6800',  dataCatigories:'women', class: 'goods__block shoes_women'},
    "448" : {src: './../womenCategory/assets/img/Обувь_4.png', name: 'GRECA SNEAKERS',                        catigories: 'Обувь', price:'4700',  dataCatigories:'women', class: 'goods__block shoes_women'},
    "449" : {src: './../womenCategory/assets/img/Обувь_5.png', name: 'ODISSEA',                               catigories: 'Обувь', price:'6200',  dataCatigories:'women', class: 'goods__block shoes_women'},
    "450" : {src: './../womenCategory/assets/img/Обувь_6.png', name: 'GRECA BAROCCO PRINT SNEAKERS',          catigories: 'Обувь', price:'4200',  dataCatigories:'women', class: 'goods__block shoes_women'},
    "451" : {src: './../womenCategory/assets/img/Обувь_7.png', name: 'CRYSTAL VERSACE ALLOVER GRECA TRAINERS',catigories: 'Обувь', price:'5600',  dataCatigories:'women', class: 'goods__block shoes_women'},
    "452" : {src: './../womenCategory/assets/img/Обувь_8.png', name: 'VERSACE GODDESS GRECA SNEAKERS',        catigories: 'Обувь', price:'5600',  dataCatigories:'women', class: 'goods__block shoes_women'},
    "453" : {src: './../womenCategory/assets/img/Обувь_9.png', name: 'GRECA MAZE CRYSTAL FLAT SANDALS',       catigories: 'Обувь', price:'6800',  dataCatigories:'women', class: 'goods__block shoes_women'},

    "454" : {src: './../womenCategory/assets/img/Штаны_1.png', name: 'VERSACE ALLOVER LEGGINGS',    catigories: 'Брюки', price:'5600',  dataCatigories:'women', class: 'goods__block pants_women'},
    "455" : {src: './../womenCategory/assets/img/Штаны_2.png', name: 'MEDUSA BIGGIE PANTS',         catigories: 'Брюки', price:'10800', dataCatigories:'women', class: 'goods__block pants_women'},
    "456" : {src: './../womenCategory/assets/img/Штаны_3.png', name: 'FLARED FORMAL PANTS',         catigories: 'Брюки', price:'6800',  dataCatigories:'women', class: 'goods__block pants_women'},
    "457" : {src: './../womenCategory/assets/img/Штаны_4.png', name: 'VERSACE ALLOVER VELVET PANTS',catigories: 'Брюки', price:'10800', dataCatigories:'women', class: 'goods__block pants_women'},
    "458" : {src: './../womenCategory/assets/img/Штаны_5.png', name: 'WIDE CARGO PANTS',            catigories: 'Брюки', price:'11700', dataCatigories:'women', class: 'goods__block pants_women'},
    "459" : {src: './../womenCategory/assets/img/Штаны_6.png', name: 'BAROCCO LEGGINGS',            catigories: 'Брюки', price:'7400',  dataCatigories:'women', class: 'goods__block pants_women'},
    "460" : {src: './../womenCategory/assets/img/Штаны_7.png', name: 'PLEATED WIDE-LEG PANTS',      catigories: 'Брюки', price:'10800', dataCatigories:'women', class: 'goods__block pants_women'},
    "461" : {src: './../womenCategory/assets/img/Штаны_8.png', name: 'LOGO CARGO PANTS',            catigories: 'Брюки', price:'11700', dataCatigories:'women', class: 'goods__block pants_women'},
    "462" : {src: './../womenCategory/assets/img/Штаны_9.png', name: 'LATEX LEGGINGS',              catigories: 'Брюки', price:'13000', dataCatigories:'women', class: 'goods__block pants_women'},

    //Новые модели
    "800" : {src: './assets/img/newTshirts_1.png', name: 'LA MASCHERA T-SHIRT',                 catigories: 'Фуфайка (Футболка)',price:'5300',  dataCatigories:'men',   dataType:'new', class: 'goods__block tshirts_men new_models'},
    "801" : {src: './assets/img/newJacket_1.png',  name: 'SINGLE-BREASTED WOOL COAT',           catigories: 'Куртка',            price:'25500', dataCatigories:'men',   dataType:'new', class: 'goods__block jacket_men new_models '},
    "802" : {src: './assets/img/newTshirts_2.png', name: 'VERSACE GODDESS SAFETY PIN T-SHIRT',  catigories: 'Фуфайка (Футболка)',price:'5000',  dataCatigories:'women', dataType:'new', class: 'goods__block tshirts_women new_models '},
    "803" : {src: './assets/img/newJacket_2.png',  name: 'MEDUSA DENIM BIKER JACKET',           catigories: 'Куртка',            price:'17800', dataCatigories:'women', dataType:'new', class: 'goods__block jacket_women new_models '},
    "804" : {src: './assets/img/newPants_1.png',   name: 'SILK AND WOOL BLEND PANTS',           catigories: 'Брюки',             price:'7200',  dataCatigories:'men',   dataType:'new', class: 'goods__block pants_men new_models'},
    "805" : {src: './assets/img/newPants_2.png',   name: `STRIPED WOOL PANTS`,                  catigories: 'Брюки',             price:'8100',  dataCatigories:'men',   dataType:'new', class: 'goods__block pants_men new_models'},
    "806" : {src: './assets/img/newJeans_1.png',   name: 'SLASHED MEDUSA JEANS',                catigories: 'Джинсы',            price:'8600',  dataCatigories:'women', dataType:'new', class: 'goods__block jeans_women new_models'},
    "807" : {src: './assets/img/newTshirts_3.png', name: `VERSACE GODDESS LONG-SLEEVED T-SHIRT`,catigories: 'Хлопковая футболка',price:'5300',  dataCatigories:'women', dataType:'new', class: 'goods__block tshirts_women new_models'},
    "808" : {src: './assets/img/newShoes_1.png',   name: 'ORCHID BAROCCO ODISSEA SNEAKERS',     catigories: 'Обувь',             price:'8100',  dataCatigories:'women', dataType:'new', class: 'goods__block shoes_women new_models'},

    //Скидочные модели
    "1200" : {src: './assets/img/disJacket_1.png', name: 'LE MASCHERE BOMBER JACKET',           catigories: 'Куртка',            oldprice:'18 100 ₽',price:'9100',  dataCatigories:'men', dataType:'discount', class: 'goods__block jacket_men discount'},
    "1201" : {src: './assets/img/disShoes_1.png',  name: 'PYTHON PRINT TRIGRECA SNEAKERS',      catigories: 'Обувь',             oldprice:'8 900 ₽', price:'4100',   dataCatigories:'men', dataType:'discount', class: 'goods__block shoes_men discount'},
    "1202" : {src: './assets/img/disPants_1.png',  name: 'WIDE CARGO PANTS',                    catigories: 'Брюки',             oldprice:'12 300 ₽',price:'6100',   dataCatigories:'women', dataType:'discount', class: 'goods__block pants_women discount'},
    "1203" : {src: './assets/img/disTshirts_1.png',name: 'VERSACE GODDESS LONG-SLEEVED T-SHIRT',catigories: 'Хлопковая футболка',oldprice:'5 300 ₽', price:'2900',   dataCatigories:'women', dataType:'discount', class: 'goods__block tshirts_women discount'},
    "1204" : {src: './assets/img/disShoes_2.png',  name: 'SLASHED ODISSEA SNEAKERS',            catigories: 'Обувь',             oldprice:'9 900 ₽', price:'8100',   dataCatigories:'men', dataType:'discount', class: 'goods__block shoes_men discount'},
    "1205" : {src: './assets/img/disHomClot_1.png',name: `VERSACE ALLOVER PAJAMA TOP`,          catigories: 'Домашняя одежда',   oldprice:'11 800 ₽',price:'5900',   dataCatigories:'men', dataType:'discount', class: 'goods__block homclot_men discount'},
    "1206" : {src: './assets/img/disShoes_2.png',  name: 'ODISSEA SNEAKERS',                    catigories: 'Обувь',             oldprice:'7 200 ₽', price:'3600',   dataCatigories:'women', dataType:'discount', class: 'goods__block shoes_women discount'},
    "1207" : {src: './assets/img/disHomClot_2.png',name: `VERSACE ALLOVER PAJAMA BOTTOMS`,      catigories: 'Домашняя одежда',   oldprice:'9 000 ₽', price:'4500',   dataCatigories:'men', dataType:'discount', class: 'goods__block homclot_men discount'},
    "1208" : {src: './assets/img/disPants_2.png',  name: 'STRIPED WOOL PANTS',                  catigories: 'Брюки',             oldprice:'8 100 ₽', price:'4050',   dataCatigories:'men', dataType:'discount', class: 'goods__block pants_men discount'},
}